#!/bin/sh

# This hook is called when a 'git pull' is done on local repository

# It does the following
# - Update GIT hooks from '.hooks' (versioned files) to '.git/hooks' (local files).
# - Currently disabled: Update Abeille version from last commit date

# Updating hooks if required
.hooks/install_hooks.sh

exit 0
# Rest is currently disabled

# Updating Abeille version
CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`    # Current branch
LAST_COMMIT_SHORT=`git rev-parse --short HEAD`      # Last commit
LAST_COMMIT_DATE=`git show -s --format=%cd --date=format:"%Y-%m-%d @%H:%M:%S" ${LAST_COMMIT_SHORT}`   # YYYY-MM-DD @HH:mm:ss
LAST_COMMIT_DATE_SHORT=`git show -s --format=%cd --date=short ${LAST_COMMIT_SHORT}` # YYYY-MM-DD
LAST_TAG=`git tag --contains ${LAST_COMMIT_SHORT}`  # Tag of the last commmit if any

# Note: If on a detached branch when doing push, CURRENT_BRANCH is empty.

if [ "${CURRENT_BRANCH}" = "stable" ]; then
    VERSION="${CURRENT_BRANCH}, ${LAST_COMMIT_DATE_SHORT}"
else
    VERSION="${CURRENT_BRANCH}, ${LAST_COMMIT_DATE}, ${LAST_COMMIT_SHORT}"
fi

echo "Mise-à-jour de la version d'Abeille: ${VERSION}"
echo "${VERSION}" > plugin_info/AbeilleVersion.inc

# Add then commit 'AbeilleVersion.inc'
git add plugin_info/AbeilleVersion.inc
git commit -m "Version update with last commit (${LAST_COMMIT_SHORT})"

# Updating Abeille version
CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`    # Current branch
LAST_COMMIT_SHORT=`git rev-parse --short HEAD`      # Last commit
LAST_COMMIT_DATE=`git show -s --format=%cd --date=format:"%Y-%m-%d @%H:%M:%S" ${LAST_COMMIT_SHORT}`   # YYYY-MM-DD @HH:mm:ss
LAST_COMMIT_DATE_SHORT=`git show -s --format=%cd --date=short ${LAST_COMMIT_SHORT}` # YYYY-MM-DD
LAST_TAG=`git tag --contains ${LAST_COMMIT_SHORT}`  # Tag of the last commmit if any

# Note: If on a detached branch when doing push, CURRENT_BRANCH is empty.

if [ "${CURRENT_BRANCH}" = "stable" ]; then
    VERSION="${CURRENT_BRANCH}, ${LAST_COMMIT_DATE_SHORT}"
else
    VERSION="${CURRENT_BRANCH}, ${LAST_COMMIT_DATE}, ${LAST_COMMIT_SHORT}"
fi

echo "Mise-à-jour de la version d'Abeille: ${VERSION}"
echo "${VERSION}" > plugin_info/AbeilleVersion.inc

# Add then commit 'AbeilleVersion.inc'
git add plugin_info/AbeilleVersion.inc
git commit -m "Version update with last commit (${LAST_COMMIT_SHORT})"

exit 0
