#!/bin/sh
# This hook is called when a 'git commit' is done on local repository

# It does the following
# - Update Abeille version file

# Updating Abeille version
CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`    # Current branch
# LAST_COMMIT_SHORT=`git rev-parse --short HEAD`      # Last commit
# LAST_COMMIT_DATE=`git show -s --format=%cd --date=format:"%Y-%m-%d %H:%M:%S" ${LAST_COMMIT_SHORT}`   # YYYY-MM-DD @HH:mm:ss
# LAST_COMMIT_DATE_SHORT=`git show -s --format=%cd --date=short ${LAST_COMMIT_SHORT}` # YYYY-MM-DD
# LAST_TAG=`git tag --contains ${LAST_COMMIT_SHORT}`  # Tag of the last commmit if any
DATE=`date +"%Y-%m-%d %H:%M:%S"`

# Note: If on a detached branch when doing push, CURRENT_BRANCH is empty.

# Note: We could put a different version according to branch name
if [ "${CURRENT_BRANCH}" = "stable" ]; then
    VERSION="${CURRENT_BRANCH}, ${DATE}"
else
    VERSION="${CURRENT_BRANCH}, ${DATE}"
fi

echo "Mise-à-jour de la version d'Abeille: ${VERSION}"
echo "${VERSION}" > plugin_info/AbeilleVersion.inc

# Add 'AbeilleVersion.inc' to current commit.
git add plugin_info/AbeilleVersion.inc

exit 0
