= Histore d une installation

== Une VM sous parallel OSX: debian 9.3.0 / Jeedom x.y.z / Abeille a.b.c

=== VM

Configuration: choisissez un réseau ponté pour avoir un IP à vous.

=== Debian

Installation de Debian des plus classique (Un gros 1/4 d'heure depuis un ISO sur disque).
Pas d'environnement de bureau, juste un serveur ssh et les utilitaires usuels système.
Une mise a jour en fin d'installation:
su -
vi /etc/apt/sources.list
# deb cdrom:[Debian GNU/Linux 9.3.0 _Stretch_ - Official amd64 DVD Binary-1 20171209-12:11]/ stretch contrib main
apt-get update
apt-get upgrade

=== Jeedom

La documentation Jeedom est à la page https://jeedom.github.io/documentation/installation/fr_FR/index

Perso j'utilise le dernier chapitre (Chapitre 10 - Autres) (Un gros 1/4 d'heure)

Connectez-vous en SSH à votre système et faites :
su -
wget https://raw.githubusercontent.com/jeedom/core/stable/install/install.sh
chmod +x install.sh
./install.sh
./install.sh -w /var/www/html  -m Jeedom
reboot

=== Web Browser

Ouvrir la page de votre Jeedom: http://Mon_IP_JEEDOM
admin/admin
Ne plus afficher et cloture fenetre du dessus.
Creation d'un Objet Abeille pour accueillir tous les futures équipement zigbee: Menu->Outils->Objets->'+', Sauvegarder et retour sur la page principale(Dashboard)

=== Ajout Plugin Abeille

Menu->Plugins->Gestion des plugins
Market
Recherche Abeille
Selectionner Abeille
Installer stable (Version 2018-06-19 01:01:07)
Voulez vous aller sur la .... -> Ok

=== Configuration du plugin









