= Installation dans un conteneur depuis Ubuntu

:toc:

== Introduction

Debian supporte nativement jeedom et le support est assuré par l'équipe de développement. Toute autre demande a propos d'une distribution est ignorée.   https://jeedom.github.io/documentation/installation/fr_FR/index

docker permet d'installer un système invité minimal dans une partie virtualisée du système hôte, tout ajout/suppression/modification du conteneur laisse tel quel le système hôte. L'interet de docker est que n'est installé que le minimum nécéssaire au fonctionnement dans l'image. ( une image éxecutée est un conteneur.) Le but ici est de faire tourner un conteneur jeedom sur un système Ubuntu, cependant ce n'est pas limité à ce système.

== Prérequis

Avoir docker disponible dans les dépôts de la distribution.


== Installation de docker

    apt-get install docker docker.io

== Fonctionnement

Loïc, un des créateurs de jeedom maintient image jeedom. Cette image appelé jeedom-server utilise une image jeedom-mysql pour stocker les données dans une base de données mysql. Il faudra donc a chaque fois lancer le conteneur jeedom-mysql puis le jeedom-server. Les réglages restent d'une fois sur l'autre.

== Récupération des images et Création des conteneurs

Ces deux lignes vont récupérer les images, créer les conteneurs et les configurer. Le port USB est a adapter selon le besoin ( `ls /dev/ttyUSB*` pour avoir la liste )

[source,bash]
docker run --name jeedom-mysql -e MYSQL_ROOT_PASSWORD=Mjeedom96 -d mysql:latest
docker run --name jeedom-server -e ROOT_PASSWORD=Mjeedom96 --link jeedom-mysql:mysql -p 9180:80 -p 9443:443 -p 9022:22 --device=/dev/ttyUSB0 jeedom/jeedom

A ce stade, l'installation de jeedom commence dans le conteneur jeedom-server. il faut compter 5 a 10 minutes selon la connexion et la puissance du système hôte.

jeedom sera disponible après quelques instants à l'adresse http://0.0.0.0:9180

TIP: Le ssh est accessible via le port 9022. (root/Mjeedom96)

== Configuration de Jeedom

Dans les champs indiqués entrer la valeur surlignée.

[width="40%",frame="topbot",options="header,footer"]
|==================================
|Database hostname| jeedom-mysql
|Database port    | 3306
|Database username| root
|Database password| Mjeedom96
|Database name    | jeedom
|Erase database   | checked
|==================================

Une fois, le texte `[END INSTALL SUCCESS]` affiché en bas. Aller à l 'adresse http://0.0.0.0:9180 la page de login de jeedom devrait apparaître. Les login et mot de passe sont admin admin.

== start/stop des conteneurs

les conteneurs peuvent être arrêtés et relancés à la demande en gardant l'ordre mysql jeedom au lancement, jeedom mysql à  l'arrêt.

Arrêt `docker stop jeedom-server && docker stop jeedom-mysql`

Démarrage `docker start jeedom-mysql && docker start jeedom-server`

== Repartir de zéro

il est possible de supprimer les conteneurs et de repartir d'un jeedom tout neuf.

`docker rm jeedom-server && docker rm jeedom-mysql`

puis aller vers link:[Récupération des images et Création des conteneurs]


== Portainer

Pour ceux que ne sont pas à l'aise avec la ligne de commande, portainer propose une interface graphique pour gérer les conteneurs et les images.
C'est un conteneur à démarrage automatique qui pourra relancer les conteneurs crées.

    docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer

le site sera disponible à l'adresse http://0.0.0.0:9000


== Installation du Plugin Abeille

voir la doc :)