= Groupes

== Intro

Les équipements peuvent être adressés par au moins deux façons:

* Adresse Zigbee courte: Les adresses courtes permettent de contacter un équipement spécifiques.
* Adresse Zigbee de groupe: Les adresses de groupes permettent de joindre un ensembles d'équipement en même temps.

Les adresses de groupe sont typiquement utilisées pas les télécommandes zigbee: Hue, Ikea,...

L'interêt est qu'un seul message sera envoyé sur le réseau zigbee, répété par tous les routeurs et tous les équipements ayant cette adresse de groupe réagiront donnant un impression d'execution simultanée.

Astuce: Ca peut aussi vous sortir d'une situation ou la couverture radio n'est pas bonne et vous avez du mal a joindre un équipement. Si vous l'adressez avec son adresse courte, le mesage doit être routé jusqu'a sa destination par une route specifique. Si vous l'adressez avec une adresse de groupe, le message va être répété par tous les routeurs et vous augmentez la chance que l'équipement recoive l'information.

Vous pouvez aussi utiliser un scenario dans jeedom pour adresser un groupe d'équipements, en envoyant à chacun d'eux une commande. Cette solution ne permet pas d'avoir l'impression d'instantanéité mais est très flexible si vous avez des produit zwave et zigbee par exemple.

Les groupes Zigbee sont nécessaires pour la gestion des scenes.

La gestion des groupes se fait depuis la ruche avec 3 commandes:

* Ajout
* Retrait
* Consultation

A chaque que fois que vous faites un ajout ou retrait, faites une Consultation pour mettre à jour les objets abeille.

Un équipement peut avoir plusieures adresses de groupes. Permet de répondre à plusieures télécommandes par exemple.

== Ajout d un groupe à un équipement

* Premier champ: adresse de l'équipement
* Deuxieme champ: End Point de l'équipement
* Troisiemen champ: l'adresse de groupe a ajouter

== Retrait d un groupe à un équipement

* Premier champ: adresse de l'équipement
* Deuxieme champ: End Point de l'équipement
* Troisiemen champ: l'adresse de groupe a retirer

== Récupérer les groupes d'un équipement

* Premier champ: adresse de l'équipement
* Deuxieme champ: End Point de l'équipement

L'information groupe doit remonter dans le champ groupe de l'équipement (peut etre invisible par defaut, le rendre visible).


