= Mise a jour

== Version stable du 16/11/2018 (ou precedentes) => Version beta du xx/xx/xxxx

Cette mise à jour est importante et délicate. Pour facilité l'integration de nouveaux équipments par la suit une standardisation des templates doit être faite.
Cela veut dire que tous les templates changent et que le objets dans Abeille/Jeedom doivent être mis à jour.

!!!! Ne pas faire ces manipulations sans avoir fait de backup !!!!

=== Solution pour les petits systemes

* Cela suppose que vous aller effacer (objets, historiques,...) toutes les données puis re-créer le réseau.
* supprimer le plug in Abeille
* Installer le plug in Abeille depuis le market (ou github)
* Activer et faire la configuration du plugin
* Demarrer le plugin
* Mettre en mode inclusion
* Appairer les devices.

=== Solution pour les gros systèmes

* Si la solution précédente demande trop de travail, on peut faire la mise à jour de la facon suivante. Attention, je ne peux pas tester toutes les combinaisons et des operations supplementaires seront certainement necessaires quand 90% aura ete fait automatiquement. 
* Mettre à jour la plugin avec le market (ou github)
* Vérifier la configuration du plugin et demarrer le plugin.
* Demander la mise à jour des objets depuis les templates, bouton: "Appliquer nouveaux modeles"
* 90% des objets devraient être à jour maintenant.

* Si un équipement ne fonctionne pas, appliquer de nouveau la mise a jour sur cet équipements uniquement. Pour ce faire dans la page Plugin->Protocol Domotique->Abeille selectionnez le device et clic sur bouton: "Apply Template". Ensuite regarder le log "Abeille_updateConfig" pour avoir le details des operations faites et eventuellement voir ce qui n'est pas mis à jour.
* vous allez trouver des messages: 
- "parameter identical, no change" qui indique que rien n'a été fait sur ce parametre (deja à jour).
- "parameter is not in the template, no change" qui indique que le parametre de l objet n'est pas trouvé dans le template. Soit il n'est plus necessaire et ne sera donc pas utilisé, soit vous l'avez changé et on le garde,...
- "Cmd Name: nom ===================================> not found in template" qui indique qu'on ne trouve pas le template pour la commande et que donc la commande n'est pas mise à jour. Ca doit être les 10% à gérer manuellement. Dans ce cas, soit effacer l objet et le recreer soit me joindre sur le forum. 